### PR TITLE
Master

### PR DESCRIPTION
**Pull request by philchung**

### CODE REVIEW

**Review by jpoon — APPROVED** [review]

**Comment by jpoon** [comment]
can you fix the conflicts?

**Comment by philchung** [comment]
It is one version number and checksum that has been changed and flagged as a conflict.  If there is an easier way to update your repo w/o a PR, let me know.  I don't have write access to your repo.

**Comment by jpoon** [comment]
you need to sync and rebate your fork

**Comment by philchung** [comment]
It is one version number and checksum that has been changed and flagged as a conflict.  Nothing else is different so nothing to rebase or refactor or sync.

**Comment by jpoon** [comment]
are you syncing and rebasing your fork against mine? 

GitHub doesn't think you are as there wouldn't be a conflict otherwise.

**Comment by philchung** [comment]
Look at the diff, only 1 file is changed w/ the version number and checksum: https://github.com/jpoon/homebrew-oci-cli/compare/master...philchung:master

If you see something different, point it out.  It was a straight fork from your repo.  I kept a different branch separate.

**Comment by jpoon** [comment]
You have 4 commits in this PR (which have all previously been merged).

You need to rebase your branch from my fork.

**Comment by jpoon** [comment]
the same merge conflicts still exist. 

I would recommend you either fix this current PR by syncing with my fork (see https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork)

or create a new PR based off of my master.

**Pull request closed without merging**
